<?php

namespace App\Services;

use App\Models\Document;
use App\Models\Project;
use App\Models\User;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\UploadedFile;

class DocumentService
{
    /**
     * Documents are listed through owned projects only. Type and search run
     * in SQL so the page never loads another homeowner's files to filter them.
     *
     * @param  array{project?: int|null, type?: string|null, search?: string|null}  $filters
     * @return array{documents: LengthAwarePaginator, projects: \Illuminate\Support\Collection, summary: object, filters: array}
     */
    public function globalIndex(User $homeowner, array $filters): array
    {
        $projects = $homeowner->projects()->orderBy('name')->get(['id', 'name', 'city', 'cover_image']);
        $ownedIds = $projects->pluck('id');

        $base = Document::query()->whereIn('project_id', $ownedIds);
        $total = (clone $base)->count();

        $documents = $this->applyFilters(clone $base, $filters, $ownedIds)
            ->with(['project', 'uploader.professionalProfile'])
            ->latest()
            ->paginate(10)
            ->withQueryString();

        return [
            'documents' => $documents,
            'projects' => $projects,
            'summary' => (object) ['total' => $total],
            'filters' => $filters,
        ];
    }

    /**
     * @param  Builder<Document>  $query
     * @param  array{project?: int|null, type?: string|null, search?: string|null}  $filters
     * @param  \Illuminate\Support\Collection<int, int>  $ownedIds
     * @return Builder<Document>
     */
    private function applyFilters(Builder $query, array $filters, $ownedIds): Builder
    {
        $projectId = (int) ($filters['project'] ?? 0);
        if ($projectId > 0 && $ownedIds->contains($projectId)) {
            $query->where('project_id', $projectId);
        }

        $type = (string) ($filters['type'] ?? '');
        if (array_key_exists($type, Document::categories())) {
            $query->where('category', $type);
        }

        $search = trim((string) ($filters['search'] ?? ''));
        if ($search !== '') {
            $term = '%'.addcslashes($search, '%_\\').'%';
            $query->where(function (Builder $inner) use ($term) {
                $inner->where('name', 'like', $term)
                    ->orWhere('description', 'like', $term)
                    ->orWhere('original_name', 'like', $term)
                    ->orWhere('category', 'like', $term)
                    ->orWhereHas('project', fn (Builder $project) => $project->where('name', 'like', $term));
            });
        }

        return $query;
    }

    /**
     * @param  array{project?: int|null, type?: string|null, search?: string|null}  $input
     * @return array{project: int|null, type: string, search: string}
     */
    public function filters(User $homeowner, array $input): array
    {
        $projectId = (int) ($input['project'] ?? 0);
        if ($projectId > 0 && ! $homeowner->projects()->whereKey($projectId)->exists()) {
            abort(404);
        }

        return [
            'project' => $projectId > 0 ? $projectId : null,
            'type' => array_key_exists((string) ($input['type'] ?? ''), Document::categories()) ? (string) $input['type'] : '',
            'search' => trim((string) ($input['search'] ?? '')),
        ];
    }

    /**
     * The stored name is generated by the disk. The original filename is kept
     * only as the download label and is never used as a path.
     */
    public function storeUpload(Project $project, User $uploader, UploadedFile $file, string $name, string $category, ?string $description = null): Document
    {
        $path = $file->store('projects/'.$project->id.'/documents', 'local');

        return $project->documents()->create([
            'uploaded_by' => $uploader->id,
            'name' => $name,
            'description' => $description,
            'original_name' => $file->getClientOriginalName(),
            'category' => $category,
            'disk' => 'local',
            'path' => $path,
            'mime' => $file->getClientMimeType(),
            'size' => $file->getSize(),
        ]);
    }
}
